services:
  httpbin:
    network_mode: host
    image: kennethreitz/httpbin
    command: ["gunicorn","-b","0.0.0.0:8080","-w","3","-k","gevent","httpbin:app"]
    # No ports with host network; service will listen on host port 80
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/ip"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    network_mode: host
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qa
    # No ports with host network; service will listen on host port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  mssql:
    network_mode: host
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    # No ports with host network; service will listen on host port 1433
    # Rely on script waiting for port 1433
