services:
  httpbin:
    image: kennethreitz/httpbin
    network_mode: host
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/ip"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:16
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    network_mode: host
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    # Rely on port 1433 availability for readiness
