#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <report.json>" >&2
  exit 2
fi

REPORT_JSON="$1"

if [[ ! -f "$REPORT_JSON" ]]; then
  echo "Report not found: $REPORT_JSON" >&2
  exit 2
fi

# Detect batch vs single-suite report
if jq -e '.suites' "$REPORT_JSON" >/dev/null; then
  # Batch report
  runAt=$(jq -r '.runAt // "(unknown run time)"' "$REPORT_JSON")
  total=$(jq -r '.summary.total' "$REPORT_JSON")
  passed=$(jq -r '.summary.passed' "$REPORT_JSON")
  failed=$(jq -r '.summary.failed' "$REPORT_JSON")
  skipped=$(jq -r '.summary.skipped' "$REPORT_JSON")
  duration=$(jq -r '.summary.duration' "$REPORT_JSON")
  echo "### HydReq batch run summary: $runAt"
  echo
  echo "- Total: $total | Passed: $passed | Failed: $failed | Skipped: $skipped | Duration(ns): $duration"
  echo
  echo "#### Suites"
  jq -r '
    .suites[] | "- Suite: \(.suite) | Total: \(.summary.total) | Passed: \(.summary.passed) | Failed: \(.summary.failed) | Skipped: \(.summary.skipped) | Duration(ns): \(.summary.duration)"' "$REPORT_JSON"
  echo
  echo "#### Tests"
  jq -r '
    def status_icon(status):
      if status == "passed" then "✅"
      elif status == "failed" then "❌"
      else "–"
      end;
    .suites[] as $s | .tests[] |
    "- \(status_icon(.status)) \(.name)\n  - suite: \($s.suite // "(unknown)")\n  - stage: \(.stage)\n  - durationMs: \(.durationMs // 0)"
  ' "$REPORT_JSON"
else
  # Single-suite report
  suite=$(jq -r '.suite // "(unknown suite)"' "$REPORT_JSON")
  total=$(jq -r '.summary.total' "$REPORT_JSON")
  passed=$(jq -r '.summary.passed' "$REPORT_JSON")
  failed=$(jq -r '.summary.failed' "$REPORT_JSON")
  skipped=$(jq -r '.summary.skipped' "$REPORT_JSON")
  duration=$(jq -r '.summary.duration' "$REPORT_JSON")
  echo "### HydReq run summary: $suite"
  echo
  echo "- Total: $total | Passed: $passed | Failed: $failed | Skipped: $skipped | Duration(ns): $duration"
  echo
  echo "#### Tests"
  jq -r '
    def status_icon(status):
      if status == "passed" then "✅"
      elif status == "failed" then "❌"
      else "–"
      end;
    .tests[] |
    "- \(status_icon(.status)) \(.name)\n  - stage: \(.stage)\n  - durationMs: \(.durationMs // 0)"
  ' "$REPORT_JSON"
fi

echo

echo "> Generated by scripts/pr-summary.sh"
