#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <report.json>" >&2
  exit 2
fi

REPORT_JSON="$1"

if [[ ! -f "$REPORT_JSON" ]]; then
  echo "Report not found: $REPORT_JSON" >&2
  exit 2
fi

# Add a small logo to the top of the markdown summary if the file exists in repo root
if [[ -f "./logo_notext.svg" ]]; then
  # GitHub renders relative images in PR comments when posted from the repo root
  echo "![HydReq](./logo_notext.svg)"
  echo
fi

# Detect batch vs single-suite report
if jq -e '.suites' "$REPORT_JSON" >/dev/null; then
  # Batch report
  runAt=$(jq -r '.runAt // "(unknown run time)"' "$REPORT_JSON")
  total=$(jq -r '.summary.total' "$REPORT_JSON")
  passed=$(jq -r '.summary.passed' "$REPORT_JSON")
  failed=$(jq -r '.summary.failed' "$REPORT_JSON")
  skipped=$(jq -r '.summary.skipped' "$REPORT_JSON")
  duration=$(jq -r '.summary.duration' "$REPORT_JSON")
  echo "### HydReq batch run summary: $runAt"
  echo
  echo "- Total: $total | Passed: $passed | Failed: $failed | Skipped: $skipped | Duration(ns): $duration"
  echo
  echo "#### Tests"
  jq -r '
    def status_icon(status):
      if status == "passed" then "✅"
      elif status == "failed" then "❌"
      else "–"
      end;
    def unknown_suite: "(unknown suite)";
    .suites[] as $s |
    "##### Suite: \($s.suite // unknown_suite)",
    "Total: \($s.summary.total) | Passed: \($s.summary.passed) | Failed: \($s.summary.failed) | Skipped: \($s.summary.skipped) | Duration(ns): \($s.summary.duration)",
    (($s.tests // [])[] | "- \(status_icon(.status)) \(.name) (stage: \(.stage), durationMs: \(.durationMs // 0))"),
    ""
  ' "$REPORT_JSON"
else
  # Single-suite report
  suite=$(jq -r '.suite // "(unknown suite)"' "$REPORT_JSON")
  total=$(jq -r '.summary.total' "$REPORT_JSON")
  passed=$(jq -r '.summary.passed' "$REPORT_JSON")
  failed=$(jq -r '.summary.failed' "$REPORT_JSON")
  skipped=$(jq -r '.summary.skipped' "$REPORT_JSON")
  duration=$(jq -r '.summary.duration' "$REPORT_JSON")
  echo "### HydReq run summary: $suite"
  echo
  echo "- Total: $total | Passed: $passed | Failed: $failed | Skipped: $skipped | Duration(ns): $duration"
  echo
  echo "#### Tests"
  jq -r '
    def status_icon(status):
      if status == "passed" then "✅"
      elif status == "failed" then "❌"
      else "–"
      end;
    (.tests // [])[] |
    "- \(status_icon(.status)) \(.name)\n  - stage: \(.stage)\n  - durationMs: \(.durationMs // 0)"
  ' "$REPORT_JSON"
fi

echo

echo "> Generated by scripts/pr-summary.sh"
