#!/usr/bin/env bash
set -euo pipefail

# Generate a PR-ready Markdown summary from a report JSON.
# Usage:
#   scripts/pr-summary.sh <report.json>

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <report.json>" >&2
  exit 2
fi

REPORT_JSON="$1"

if [[ ! -f "$REPORT_JSON" ]]; then
  echo "Report not found: $REPORT_JSON" >&2
  exit 2
fi

suite=$(jq -r '.suite // "(unknown suite)"' "$REPORT_JSON")
total=$(jq -r '.summary.total' "$REPORT_JSON")
passed=$(jq -r '.summary.passed' "$REPORT_JSON")
failed=$(jq -r '.summary.failed' "$REPORT_JSON")
skipped=$(jq -r '.summary.skipped' "$REPORT_JSON")
duration=$(jq -r '.summary.duration' "$REPORT_JSON")

echo "### HydReq run summary: $suite"
echo
echo "- Total: $total | Passed: $passed | Failed: $failed | Skipped: $skipped | Duration(ns): $duration"
echo
echo "#### Tests"
jq -r '
  def status_icon(status):
    if status == "passed" then "✅"
    elif status == "failed" then "❌"
    else "–"
    end;

  .tests[] |
  "- \(status_icon(.status)) \(.name)\n  - stage: \(.stage)\n  - durationMs: \(.durationMs // 0)"
' "$REPORT_JSON"

echo
echo "> Generated by scripts/pr-summary.sh"
